{
 "title": "Manual Booth",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Input_Boolean", "query": "${VAR_INPUT_BOOLEAN}" },
   { "name": "Entity", "query": "${VAR_ENTITY}" },
   { "name": "Sensor", "query": "${VAR_SENSOR}" },
   { "name": "Title", "query": "${VAR_TITLE}" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "measurement": "/^$Input_Boolean$/",
     "query": "SELECT \"state\" FROM \"input_boolean.dryer_on\" WHERE (\"entity_id\" = 'dryer_on') AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/^$Entity$/" }
     ]
    }
   ]
  },
  {
   "title": "$Title Hours Last 7 Days",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h",
     "query": "SELECT max(\"value\") FROM \"h\" WHERE (\"entity_id\" = 'paint_line_on') AND $timeFilter GROUP BY time(1d) fill(none) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/^$Sensor$/" }
     ],
     "tz": "America/Chicago"
    }
   ]
  },
  {
   "title": "$Title Hours Last 7 Days",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/^$Sensor$/" }
     ],
     "tz": "America/Chicago"
    }
   ]
  },
  {
   "title": "$Title Hours This Month So Far",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "$Title Hours This Year So Far",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  }
 ]
}